Comment out line of dead code
UCLA-Rocket-Project/AresSoftware pull request #2
Opened 2022-10-05 09:37 UTC by atpngo

swag moneyyy

2022-10-05 17:08 UTC, harrisonCassar requested changes

2022-10-05 17:08 UTC, harrisonCassar commented on Arduino/Ground Systems/Controls/controls.ino
> +          // int pin = pins[j - 1];
I'm in favor of just removing the line altogether. If we need it in the future, we can utilize version control to get it back.

2022-10-05 17:08 UTC, harrisonCassar commented on Arduino/Ground Systems/Controls/controls.ino
>        {
Also, can't seem to make a comment on the specific line, but the same removal should also apply to the global `pins` array init on Line 6: https://github.com/UCLA-Rocket-Project/AresSoftware/blob/main/Arduino/Ground%20Systems/Controls/controls.ino#L6

2022-10-06 07:39 UTC, atpngo commented on Arduino/Ground Systems/Controls/controls.ino
>        {
for sure! i thought it would be best for antonio to handle commenting out/deleting that line just for the sake of getting familiar with the github workflow

2022-10-06 07:51 UTC, harrisonCassar approved these changes

2022-10-06 07:51 UTC, harrisonCassar commented on Arduino/Ground Systems/Controls/controls.ino
>        {
Ah, makes sense! We'll leave it up to him, then, to remove that!

2022-10-06 07:51 UTC, harrisonCassar commented
Ready for squah/merge!

2022-10-06 08:05 UTC, philipdoucla approved these changes
lgtm!

2022-10-06 08:06 UTC, merged